---

- name: Configuring CHROOT templates - managing container directory
  file:
    path: "{{ hm_alchemist__home_chroots }}"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Configuring CHROOT templates - performing debootstrap
  shell: "debootstrap {{ chroot_suite }} {{ hm_alchemist__home_chroots }}/{{ chroot_name }} {{ hm_alchemist__debootstrap_url }}"
  args:
    creates: "{{ hm_alchemist__home_chroots }}/{{ chroot_name }}"

- name: Configuring CHROOT templates - naming chroot
  shell: "echo '{{ chroot_name }}' > {{ hm_alchemist__home_chroots }}/{{ chroot_name }}/etc/debian_chroot"
  args:
    creates: "{{ hm_alchemist__home_chroots }}/{{ chroot_name }}/etc/debian_chroot"

- name: Configuring CHROOT templates - installing configuration files
  shell: "rsync {{ item }} {{ hm_alchemist__home_chroots }}/{{ chroot_name }}{{ item }}"
  with_items:
    - /etc/hosts
    - /etc/apt/sources.list

- name: Configuring CHROOT templates - divert buggy ischroot
  shell: "chroot {{ hm_alchemist__home_chroots }}/{{ chroot_name }} dpkg-divert --divert /usr/bin/ischroot.debianutils --rename /usr/bin/ischroot"
  args:
    creates: "{{ hm_alchemist__home_chroots }}/{{ chroot_name }}/usr/bin/ischroot.debianutils"

- name: Configuring CHROOT templates - Fix ischroot
  file:
   src: "{{ hm_alchemist__home_chroots }}/{{ chroot_name }}/bin/true"
   dest: "{{ hm_alchemist__home_chroots }}/{{ chroot_name }}/usr/bin/ischroot"
   state: link

- name: Configuring CHROOT templates - upgrading system packages
  shell: "chroot {{ hm_alchemist__home_chroots }}/{{ chroot_name }} apt-get update && apt-get upgrade -y"

- name: Configuring CHROOT templates - installing system packages
  shell: "chroot {{ hm_alchemist__home_chroots }}/{{ chroot_name }} apt-get install -y {{ item }}"
  with_items: "{{ chroot_pkgs_deb }}"

- name: Configuring CHROOT templates - installing python packages
  shell: "chroot {{ hm_alchemist__home_chroots }}/{{ chroot_name }} apt-get install -y {{ item }}"
  with_items: "{{ hm_alchemist__deb_packages_python[chroot_python] }}"

- name: Configuring CHROOT templates - Installing special files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - {
        "src": "policy-rc.d",
        "dest": "{{ hm_alchemist__home_chroots }}/{{ chroot_name }}/usr/sbin/policy-rc.d",
        "mode": "0755"
      }
