---

- debug:
    msg: "Managing project {{ project_name }}"
  tags:
    - debug

- name: "Managing project directories for {{ project_name }}"
  file:
    path: "{{ hm_alchemist__home_projects }}/{{ project_name }}"
    owner: "{{ project_name }}"
    group: "{{ hm_alchemist__account_buildbot }}"
    mode: "2775"
    state: directory

- name: "Managing project metadata for {{ project_name }}"
  template:
    src: project.metadata.json.j2
    dest: "{{ hm_alchemist__home_projects }}/{{ project_name }}/.metadata.json"
    owner: "{{ project_name }}"
    group: "{{ hm_alchemist__account_buildbot }}"
    mode: 0644
    backup: yes

- include_tasks: _inc.initgitrepo.yml

- include_tasks: _inc.initfilerepo.yml

- include_tasks: _inc.initdocrepo.yml
  when: "'doc' in project_data['build']['modules']"

- include_tasks: _inc.initdebrepo.yml
  when: "'deb' in project_data['build']['modules']"
