---

- debug:
    msg: "Configuring virtualenv for {{ worker }}"
  with_items: "{{ ri_venv_packages }}"
  tags:
    - debug

- name: Configuring virtualenv for worker
  pip:
    name: "{{ item }}"
    virtualenv: "/home/buildbot/workers/{{ worker }}/venv"
    state: latest
  become: true
  become_user: "{{ hm_alchemist__account_buildbot }}"
  with_items: "{{ ri_venv_packages }}"
