---

- debug:
    msg: "Configuring virtualenv for {{ worker }}: {{ ri_venv_packages }}"
  tags:
    - debug

- name: Installing Python packages to virtualenv for worker
  pip:
    name: "{{ ri_venv_packages }}"
    virtualenv: "/home/buildbot/workers/{{ worker }}/venv"
    state: latest
  become: true
  become_user: "{{ hm_alchemist__account_buildbot }}"
