---

- name: Including secret configurations
  include_vars: "vault/secrets.yml"
  tags:
    - always

#-------------------------------------------------------------------------------

- name: Build master directory must be defined and contain sane value
  assert:
    that:
      - "hm_alchemist__home_buildmaster is defined"
      - "hm_alchemist__home_buildmaster != '/'"
    fail_msg: "'hm_alchemist__home_buildmaster' must be defined and not '/'"
    success_msg: "'hm_alchemist__home_buildmaster' looks sane"

- name: Build worker directory must be defined and contain sane value
  assert:
    that:
      - "hm_alchemist__home_buildworkers is defined"
      - "hm_alchemist__home_buildworkers != '/'"
    fail_msg: "'hm_alchemist__home_buildworkers' must be defined and not '/'"
    success_msg: "'hm_alchemist__home_buildworkers' looks sane"

- name: Project directory must be defined and contain sane value
  assert:
    that:
      - "hm_alchemist__home_projects is defined"
      - "hm_alchemist__home_projects != '/'"
    fail_msg: "'hm_alchemist__home_projects' must be defined and not '/'"
    success_msg: "'hm_alchemist__home_projects' looks sane"

- block:

    - import_tasks: install.debian.yml
      tags:
        - install

    - import_tasks: configure.debian.yml
      tags:
        - configure

  when: ansible_os_family == 'Debian'
